name: Docker Image CI (main)

on:
  push:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  schedule:
  # Run roughly every 15 days at 00:00 UTC
  # (useful to check if updates on dependencies break the package)
  - cron: '0 0 1,16 * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.HUB_DOCKER_COM_OPENSEMANTICWORLD_USERNAME }}
        password: ${{ secrets.HUB_DOCKER_COM_OPENSEMANTICWORLD_PASSWORD }}
      
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: opensemanticworld/h2ogpt-cpu
      
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: build/
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}